### ISSUE TITLE
Description swap

### ISSUE THREAD

**Issue by tsuyoshicho** [iwataka/vim-markdown-ex#1]
https://github.com/iwataka/vim-markdown-ex/blob/3f6c96f4ae64ac4db2ccd98ae79d43ff0d13b75a/doc/vim-markdown-ex.txt#L53-L59

`ic` is inner, `ac` is around.

I think this is.

**Comment by iwataka** [comment]
Thank you for reporting the issue!
Fix this by PR #2 .
